# Generated by Django 5.1 on 2025-01-23 18:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailSender',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(help_text='The subject of the email.', max_length=128, verbose_name='Subject')),
                ('emails', models.TextField(help_text='Emails should be separated by comma. Example: 123@mail.com,1234@gmail.com', verbose_name='Emails')),
                ('message', models.TextField(help_text='Emails should be separated by comma. Example: 123@mail.com,1234@gmail.com', verbose_name='Emails')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'MailSender',
                'verbose_name_plural': 'MailSenders',
            },
        ),
    ]
