# Generated by Django 5.1 on 2025-01-11 12:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maillisting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Full name')),
                ('email', models.EmailField(max_length=128, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Maillisting',
                'verbose_name_plural': 'Maillistings',
            },
        ),
    ]
