name: Deploy to AWS Instance

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Connect to AWS Instance and Deploy
    - name: Deploy to AWS Instance
      env:
        AWS_HOST: ${{ secrets.AWS_HOST }}
        AWS_USER: ${{ secrets.AWS_USER }}
        PRIVATE_KEY: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
      run: |
        # Save the private key for SSH access
        echo "$PRIVATE_KEY" > aws_instance_key.pem
        chmod 600 aws_instance_key.pem

        # SSH into the AWS instance
        ssh -i aws_instance_key.pem $AWS_USER@$AWS_HOST << EOF
          # Navigate to the project directory
          cd /path/to/your/project

          # Pull the latest changes from GitHub
          git pull origin main

          # Rebuild the Docker containers
          docker-compose down
          docker-compose up -d --build

          # Optionally clean up old images
          docker image prune -f
        EOF

        # Clean up private key
        rm -f aws_instance_key.pem