name: Deploy to AWS Instance

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Deploy to AWS Instance
    - name: Deploy to AWS Instance
      env:
        AWS_HOST: ${{ secrets.AWS_HOST }}
        AWS_USER: ${{ secrets.AWS_USER }}
        PRIVATE_KEY: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
      run: |
        echo "Starting deployment to $AWS_HOST"
        echo "$PRIVATE_KEY" > aws_instance_key.pem
        chmod 600 aws_instance_key.pem

        mkdir -p ~/.ssh
        ssh-keyscan -H $AWS_HOST >> ~/.ssh/known_hosts

        ssh -v -i aws_instance_key.pem $AWS_USER@$AWS_HOST 'bash -s' << 'EOF'
          set -e
          echo "SSH connected to $AWS_HOST"

          cd simple_backend
          echo "Pulling latest changes..."
          git pull origin main

          echo "Rebuilding Docker containers..."
          docker-compose -f docker/docker-compose-dev.yml down
          docker-compose -f docker/docker-compose-dev.yml up --build -d

          echo "Cleaning up old Docker images..."
          docker image prune -f

          echo "Deployment complete!"
        EOF

        rm -f aws_instance_key.pem
